### ISSUE TITLE
I need sub commands for global installing and update It self

### ISSUE THREAD

**Issue by NanamiTakayama** [xshellinc/iotit#14]
I want dommand like "iotit gl" for install as global command.
and "iotit update" for update itself.

**Comment by larenso** [comment]
Currently iotit has `-update <sd|edison>`, which updates vboxes
Or you want smth different? Like auto-update the binary?

**Comment by dbsparkle** [comment]
I think @NanamiTakayama is talking about `self-update`...

It would also be nice to have these commands:

```
global, gl     Use this command to install to global app environment
uninstall, un  Use this command to uninstall this app
```

**Comment by larenso** [comment]
installation now will copy binary into `/usr/local/bin`

**Comment by bnuriddin** [comment]
uploaded version.json to cdn
