### ISSUE TITLE
Wifi credentials not set

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#2]
I flashed three times and seems like the wifi credentials were not set any time. I could flash with the previous version of `isaax cli` and it was set correctly.

Ive attached the log.

[iotit.log.zip](https://github.com/xshellinc/iotit/files/775938/iotit.log.zip)

**Comment by e-asphyx** [comment]
Something wrong with copying files to mounted image (or with image mounting).
Command executed on virtual machine after image (possible) unmounting:

```
localhost:~# cat /tmp/isaax-sd/etc 
KEYMAP=us 
```

So it's a regular file

```
localhost:~# cat /root/wpa_supplicant.conf 
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev 
update_config=1 

network={ 
	ssid="Plan-B" 
	psk="coh5that" 
}
```

wpa_supplicant.conf seems to be copied into /root dir

Still figuring out
