### ISSUE TITLE
Wifi doesn't work when setting static ip

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#25]
Using development version of iotit.

When I flash device and set static ip the device does not get any ip address and cannot connect to wifi then without a lan connect. If i do not set static ip then the i can connect to wifi.

I have tested on raspberry and nano pi so far. On edison setting static ip resulted in #22 

[iotit.log.zip](https://github.com/xshellinc/iotit/files/829695/iotit.log.zip)

**Comment by e-asphyx** [comment]
I'll get an ethernet cable and make some tests.
