### ISSUE TITLE
Crash on flashing attempt

### ISSUE THREAD

**Issue by e-asphyx** [xshellinc/iotit#31]
[+] flashing: - panic: runtime error: slice bounds out of range

goroutine 224 [running]:
github.com/xshellinc/tools/lib/sudo.Exec.func1(0xc420518fc0, 0xc420518d20, 0xc4202ab180, 0x1389158, 0x12f8aa0, 0xc42030b740, 0x14d8400, 0xc420353280)
	/Users/asphyx/Projects/go/src/github.com/xshellinc/tools/lib/sudo/sudo.go:71 +0x419
created by github.com/xshellinc/tools/lib/sudo.Exec
	/Users/asphyx/Projects/go/src/github.com/xshellinc/tools/lib/sudo/sudo.go:83 +0x346

**Comment by e-asphyx** [comment]
Fixed here https://github.com/xshellinc/tools/tree/feature/fix-sudo-prompt

**Comment by larenso** [comment]
@e-asphyx if fixed, pls close the issue
