### ISSUE TITLE
add option to scp files to OS image

### ISSUE THREAD

**Issue by kylycht** [xshellinc/iotit#45]
Add option where user can scp files to a desired dir in OS image:

In our case we can upload isaax-agent binary along with registration token
**NOTE: Token should be present in ONE of these options**

Order of token lookup:
1. Environment variable `ISAAX_TOKEN`
2. Read from file `~/.isaax_token`
3. Read from file `/etc/.isaax_token`

**Comment by kylycht** [comment]
this will allow us to upload `isaax-agent`,`isaax_token`(registration token) during `init`

**Comment by dbsparkle** [comment]
@kylycht 

1. Does it mean that we will have files `~/.isaax_token` and `/etc/.isaax_token` ?
2. _this will allow us to upload isaax-agent, isaax_token during `init`_ - what is `init` here?

**Comment by kylycht** [comment]
@dbsparkle it is not required. it is ONE of the options. Agent will lookup for environment variable in that order. In some cases there might be no `~`(home dir for user), 
in that case it can be placed in `/etc/.isaax_token`

The order is: 
1. Lookup envar
2. If envar does not exist, lookup in home dir
3. If home dir does not exist, lookup in `/etc/`

we do fallbacks to ~ and /etc/ if envar is not present

> NOTE: Token should be present in ONE of these options

`init` - when we initialize the SBC

**Comment by kylycht** [comment]
So there might be a prompt something like:


```
[+] Would you like to upload additional files?(y/n):
#if user selects yes
[+] Please enter full path to your file: /tmp/registration_token_file
[+] Please enter destination dir: /etc/.isaax_token
```

**Comment by dbsparkle** [comment]
Maybe it should be a common file, something like `etc/.isaax_config`?

**Comment by kylycht** [comment]
@dbsparkle we can name it `.isaax_config`, but it is going to contain only a token

**Comment by dbsparkle** [comment]
https://github.com/xshellinc/iotit/issues/45#issuecomment-289799318

Keep in mind footprint problem @kylycht

**Comment by kylycht** [comment]
@dbsparkle yep, need to review `isaax-agent` config file and remove what can be removed

**Comment by larenso** [comment]
can be created smth like `./iotit/sd-copy/`

and all the content of the `sd-copy` will be copied to `sd_card` recursively replacing files
i.e. `./iotit/sd-copy/etc/dhcpcd.conf` copy and replace if exists `/etc/dhcpcd.conf`

**Comment by dbsparkle** [comment]
@kylycht @tectiv3 I think we should close this issues as an abandoned one
