### ISSUE TITLE
Should we add option to install vbox?

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#50]
If the user does not have vbox installed should we offer to install it?

**Comment by larenso** [comment]
I don't think so, user can install vbox via different ways, i.e. repo/binary installation and etc. I think that notification is to install vbox is enough. Inexperienced users can just go to virtualbox page and download binary from there

**Comment by makeupsomething** [comment]
Yeah i see your point. Maybe its not needed. 

I was just thinking that for something like Etcher i do not need to install anything else to make it work.
