### ISSUE TITLE
Remove install software option 

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#54]
```
  [+]curl
  [+]bluez
  [+]iptables
  [+]openssh-server
  [+]openssh-client
  [+]locales
  [+]tzdata
  [+]sudo
  [+]bash
  [+]unzip
  [+]tar
  [+]find
  [+]nano
  [+]git
[?] Would you like to install basic software for your device? (y/yes OR n/no):n
```

I guess we should just remove this. Its not our responsibility and I think it does not work at the moment anyway. We would be better off to expand the range of images we support that already include these software such as for #47

**Comment by larenso** [comment]
here https://github.com/xshellinc/iotit/issues/55
