### ISSUE TITLE
Add option to turn ssh on for raspberry 

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#62]
As latest version of raspian has ssh off by default https://www.raspberrypi.org/blog/a-security-update-for-raspbian-pixel/
We need an option to turn it on when configuring board. 
Something like:

```
[+] Would you like to turn on ssh by default? (y/n)
```

We should provide an option for the user to turn on or not, when he is configuring a board.

**Comment by larenso** [comment]
@makeupsomething can you find any of `K??ssh` or `S02ssh` in `/etc/rc2.d/`
`??` - stands for 01, 11, 02 and etc

**Comment by larenso** [comment]
added ssh empty file into boot partition

**Comment by makeupsomething** [comment]
@larenso this is working, but it should be an option for the user to turn on or not. Can you add it as an option when the user is configuring board?
