### ISSUE TITLE
Include 7zip in issax virtual machine

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#63]
We need to include this for custom image installation

**Comment by dbsparkle** [comment]
@makeupsomething why do we need 7zip in VM?

`apt-get install zip unzip` vs `apt-get install p7zip-full`

**Comment by makeupsomething** [comment]
I tried to flash ambian and it downloaded as a 7z file. Iotit then crashed as it could not extract a 7z file.

**Comment by larenso** [comment]
Added changes, @bnuriddin updated the image on the cloud

**Comment by dbsparkle** [comment]
@makeupsomething check pls, if there is no problem then lets close this issue
