### ISSUE TITLE
How can I confirm the correct mounting point?

### ISSUE THREAD

**Issue by yutashi** [xshellinc/iotit#77]
version: iotit-0.2.1  
platform: mac OS

How can I confirm the correct mounting point to answer following question?
```
[+] Uploading 2017-04-10-raspbian-jessie-lite.img to virtual machine
   [1] loop0p1
   [2] loop0p2
[?] Please select the correct mounting point:
```

**Comment by makeupsomething** [comment]
@tectiv3 Is there a way to make it more clear to the user which mounting point to use?

**Comment by dbsparkle** [comment]
@makeupsomething @yutashi 
Read about loop here:  https://en.m.wikipedia.org/wiki/Loop_device

**Comment by dbsparkle** [comment]
Simply think that loops are your partitions

**Comment by makeupsomething** [comment]
> Simply think that loops are your partitions

We need a way to make that clear to the user when using iotit then, not sure how though. Unless theres some heuristic we can use to make a best guess at which one they should choose. If they use the default virtual machine its usually the second one.

**Comment by dbsparkle** [comment]
@yutashi @makeupsomething TYI:

http://man7.org/linux/man-pages/man8/mount.8.html#THE_LOOP DEVICE

```
One further possible type is a mount via the loop device.  For
       example, the command

              mount /tmp/disk.img /mnt -t vfat -o loop=/dev/loop3

       will set up the loop device /dev/loop3 to correspond to the file
       /tmp/disk.img, and then mount this device on /mnt.

       If no explicit loop device is mentioned (but just an option `-o loop'
       is given), then mount will try to find some unused loop device and
       use that, for example

              mount /tmp/disk.img /mnt -o loop

       The mount command automatically creates a loop device from a regular
       file if a filesystem type is not specified or the filesystem is known
       for libblkid, for example:

              mount /tmp/disk.img /mnt

              mount -t ext3 /tmp/disk.img /mnt

       This type of mount knows about three options, namely loop, offset and
       sizelimit, that are really options to losetup(8).  (These options can
       be used in addition to those specific to the filesystem type.)

       Since Linux 2.6.25 auto-destruction of loop devices is supported,
       meaning that any loop device allocated by mount will be freed by
       umount independently of /etc/mtab.

       You can also free a loop device by hand, using losetup -d or umount
       -d.

       Since util-linux v2.29 mount command re-uses the loop device rather
       than initialize a new device if the same backing file is already used
       for some loop device with the same offset and sizelimit. This is
       necessary to avoid a filesystem corruption.
```

**Comment by tectiv3** [comment]
To be honest, I don't think we even need this dialog. It's confusing for the user and not much of a help for us.
We can either mount every loop device we find inside chosen image and then figure out which one is linux root partition ourselves or always mount the second one because it would be a raspberry pi image anyway.

**Comment by makeupsomething** [comment]
@tectiv3 If we can get rid of it then we should. It is not much use to the user.

**Comment by dbsparkle** [comment]
Still it's worth mentioning about in documents

**Comment by tectiv3** [comment]
@dbsparkle mentioning what? that we will automatically detect root partition?

**Comment by dbsparkle** [comment]
Mentioning "how we detect the partitions"
