### ISSUE TITLE
Add flash support for Toradex Colibri iMX6 board.

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#85]
We were able to flash this board manually, it is similar in some ways to how you flash edison.
We were basically following this guide http://developer.toradex.com/knowledge-base/flashing-linux-on-imx6-modules

Here is the sequence of steps we took to flash the board.

### Prepare SD card

- Download linux image from toradex site from here http://developer1.toradex.com/files/toradex-dev/uploads/media/Colibri/Linux/Images/

- Extract image as root like `sudo tar xjvf <fileName>`

- Find your SD card mount point with command `df`

- In the image folder there is script called `update.sh`, run this script with the mount point of your SD card as a parameter like this `./update.sh -o /media/KERNAL`

### Connect to the board

- Connect your toradex board to your host machine and find which port it is connected to. You can use a command like `sudo dmesg | grep tty` to find which port.

- Connect to the board using a screen with this command `sudo screen -T vt100 /dev/<port> 115200`

- Reboot the board and enter `Recovery Mode`. You do this by pressing the spacebar key before linux starts to boot. Or it can also be done by using tweezers to short 2 pins on the board (see image in the documentation)

### Flash

- Insert your prepared SD card into the board.

- Run the command `run setupdate`

- Run the command `run update`

- The device will begin flashing sequence

This will be complicated to develop as you do not have the board and it may not be that easy (cheap) to get. So it will take lots of co-operation and frustration to get it done. We want to finish this in August.

**Comment by dbsparkle** [comment]
Issue moved to [xshellinc/isaax-main #248](https://github.com/xshellinc/isaax-main/issues/248) via [**ZenHub**](https://www.zenhub.com/)
