### ISSUE TITLE
Micropython flashing for ESP

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#90]
Is it possible to add function to flash micropython to ESP devices? 
Should we add it?

@tectiv3 @dbsparkle @yutashi

**Comment by yutashi** [comment]
It is possible that goes against of the technical conformity if ESP with microPython uses Wifi and BLE in Japan.

**Comment by tectiv3** [comment]
It is possible.
We can add it along with Arduino core in the future. Currently we only support (and concentrate our efforts on) our own Firmata firmware though.
