### ISSUE TITLE
Cannot change locale

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#92]
When flash and set a new locale using iotit this error appears on raspberry pi 2 when booting up.

`-bash: warning: setlocale: LC_ALL: cannot change locale (uk_UA.utf8)
`

**Comment by dbsparkle** [comment]
@makeupsomething uk_UA.utf8 is Ukraine locale...

**Comment by tectiv3** [comment]
yeah, you've set it manually at configuration step?

**Comment by makeupsomething** [comment]
@tectiv3 yep

**Comment by tectiv3** [comment]
well, it means you need to run `sudo locale-gen uk_UA` and `sudo dpkg-reconfigure locales`
and @dbsparkle is right it's a ukrainian locale

**Comment by dbsparkle** [comment]
I am wondering why Ukrainian locale has been set as default? :)

**Comment by makeupsomething** [comment]
@tectiv3 Why do I have to run it? Should it not have been set by iotit?

Why is everyone mentioning that it is Ukraine? :)

**Comment by makeupsomething** [comment]
@dbsparkle not by default, i set it during configuration

**Comment by tectiv3** [comment]
@dbsparkle don't look at me I don't use ukrainian locale:)

**Comment by tectiv3** [comment]
@makeupsomething well, this is needs to be run on an actual system. iotit only prepares the image.
ofc we can make some sort of startup script that run only on a first boot. But that wouldn't look good I think.

**Comment by makeupsomething** [comment]
> ofc we can make some sort of startup script that run only on a first boot

Not necessary i think. Closing this issue.
