### ISSUE TITLE
Error updating iotit

### ISSUE THREAD

**Issue by makeupsomething** [xshellinc/iotit#94]
When i run `iotit update` I get this error. It is latest version on develop branch.

```
iotit update
[+] Current os:  darwin amd64
[-] Error: strconv.Atoi: parsing "": invalid syntax
```

**Comment by tectiv3** [comment]
This one is tricky. Since we moved to github releases and goreleaser we are no longer update
http://iotit.s3-website-us-west-2.amazonaws.com/version.json

I need to find a way to replicate it's functionality with github.

**Comment by dbsparkle** [comment]
@tectiv3 what about this issue?

**Comment by tectiv3** [comment]
well, I was planning on handling it this week. Probably even today.
It's disabled atm so it won't affect the release and since we are distributing iotit through package managers now (brew and linux native packages) I guess it's not a big problem.
